### ISSUE TITLE
Header fixes.

### ISSUE THREAD

**Issue by brunobraga95** [brunobraga95/mive#2]
![image](https://user-images.githubusercontent.com/14654063/40271014-e448a002-5b6d-11e8-97fb-14678836047c.png)

1.  - [x] Remove left button
2.  - [ ] Update project name
3.  - [ ] fix right icon margin (seems too large)

**Comment by AndreAffonso** [comment]
**2. Update project name** 
 - Should I update with the project name or with the current company name??

**Comment by brunobraga95** [comment]
good question... ir should be the project name during the QR code screen, and the current company after the check in.

what you think?

**Comment by brunobraga95** [comment]
ops

**Comment by AndreAffonso** [comment]
I was thinking the same thing. We could get the URL params to handle with this.
For example:

- Route "/": The header should display the PROJECT_NAME
- Route /company-name/table-number": The header should display the COMPANY_NAME

**Comment by brunobraga95** [comment]
awesome, you can create a company name selector inside `containers/company`
